pipeline {
    agent {label 'docker'}
    stages {
        stage('Greeting') {
            steps {
                sh 'echo Hello from test branch'
            }
        }
        stage('preparation') {
            steps {
                git 'https://https://github.com/AbdelrahmanAdelTaha/pyflask-app-example.git'
            }
        }
        stage('Build') {
            steps {
                sh 'sudo docker build . -t abdelrahmanadel97/pyflask-app:v1.0'
            }
        }
        stage('Deploy') {
            steps {
                sh 'sudo docker run -d -p 5005:5000 abdelrahmanadel97/pyflask-app:v1.0'
            }

            post{
                success{
                    slackSend(color:'#47d147', message:'All steps have been completed successfully for our app in AWS_ec2_Slave')
                }
                failure{
                    slackSend(color:'#ff0000', message:'process faild in Docker_Slave_Container')
                }
            }
        }
    }
}